AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  learn-hub-app

  Sample SAM Template for learn-hub-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
    Runtime: python3.14
    CodeUri: src/
  Api:
    TracingEnabled: true
    Auth:
      DefaultAuthorizer: CognitoAuthorizer

      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt LearnHubUserPool.Arn
Resources:
  HealthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: handlers.health.lambda_handler
      Architectures:
      - x86_64
      Events:
        Health:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: get

            Auth:
              Authorizer: NONE
  CoursesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: handlers.courses.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref LearnHubTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LearnHubTable
        - DynamoDBWritePolicy:
            TableName: !Ref LearnHubTable
      Architectures:
      - x86_64
      Events:
        Courses:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /courses
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
              AuthorizationScopes:
                - aws.cognito.signin.user.admin


  LearnHubTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub learnhub-${AWS::StackName}

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  LearnHubUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub learnhub-${AWS::StackName}-users

      UsernameAttributes:
        - email

      AutoVerifiedAttributes:
        - email

      UsernameConfiguration:
        CaseSensitive: false

      LambdaConfig:
        PostConfirmation: !GetAtt PostConfirmationPublisherFunction.Arn

      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7

      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

      MfaConfiguration: "OFF"

      DeletionProtection: INACTIVE

  LearnHubUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub learnhub-${AWS::StackName}-client
      UserPoolId: !Ref LearnHubUserPool

      GenerateSecret: false

      PreventUserExistenceErrors: ENABLED

      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30

      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  LearnHubEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: learnhub

  PostConfirmationPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.post_confirmation.lambda_handler
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref LearnHubEventBus
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref LearnHubEventBus

  PostConfirmationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PostConfirmationPublisherFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt LearnHubUserPool.Arn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HealthApi:
    Description: API Gateway endpoint URL for Prod stage for Health
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/health/"
  HealthFunction:
    Description: Health Lambda Function ARN
    Value: !GetAtt HealthFunction.Arn
  HealthFunctionIamRole:
    Description: Implicit IAM Role created for Health function
    Value: !GetAtt HealthFunctionRole.Arn

  LearnHubUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref LearnHubUserPool

  LearnHubUserPoolArn:
    Description: Cognito User Pool Arn
    Value: !GetAtt LearnHubUserPool.Arn

  LearnHubUserPoolClientId:
    Description: Cognito App Client ID
    Value: !Ref LearnHubUserPoolClient
